"""
SQL guard module for the Hybrid AI Predictive Maintenance project.

This module validates SQL queries generated by a Text-to-SQL layer.
For safety, only read-only SELECT queries are allowed.
"""

import re


FORBIDDEN_KEYWORDS = {
    "insert",
    "update",
    "delete",
    "drop",
    "alter",
    "truncate",
    "create",
    "replace",
    "attach",
    "detach",
    "pragma",
    "vacuum",
}


def normalize_sql(sql_query: str) -> str:
    """Normalize SQL text for validation."""
    return sql_query.strip().lower()


def has_multiple_statements(sql_query: str) -> bool:
    """Check whether the query contains multiple SQL statements."""
    stripped_query = sql_query.strip()

    if not stripped_query:
        return False

    semicolon_count = stripped_query.count(";")

    if semicolon_count == 0:
        return False

    return not stripped_query.endswith(";") or semicolon_count > 1


def starts_with_select(sql_query: str) -> bool:
    """Check whether the query starts with SELECT."""
    normalized_query = normalize_sql(sql_query)
    return normalized_query.startswith("select")


def contains_forbidden_keywords(sql_query: str) -> bool:
    """Check whether the query contains forbidden SQL keywords."""
    normalized_query = normalize_sql(sql_query)

    tokens = re.findall(r"\b[a-z_]+\b", normalized_query)

    return any(token in FORBIDDEN_KEYWORDS for token in tokens)


def validate_sql_query(sql_query: str) -> tuple[bool, str]:
    """
    Validate a SQL query.

    Returns:
        tuple[bool, str]: validation status and message.
    """
    if not sql_query or not sql_query.strip():
        return False, "SQL query is empty."

    if has_multiple_statements(sql_query):
        return False, "Only one SQL statement is allowed."

    if not starts_with_select(sql_query):
        return False, "Only SELECT queries are allowed."

    if contains_forbidden_keywords(sql_query):
        return False, "Query contains forbidden SQL keywords."

    return True, "SQL query is valid."


def main() -> None:
    """Run manual validation examples."""
    test_queries = [
        "SELECT * FROM scenarios;",
        "select asset_name from assets",
        "DELETE FROM assets;",
        "DROP TABLE scenarios;",
        "SELECT * FROM assets; DROP TABLE assets;",
        "",
    ]

    for query in test_queries:
        is_valid, message = validate_sql_query(query)
        print(f"Query: {query!r}")
        print(f"Valid: {is_valid}")
        print(f"Message: {message}")
        print("-" * 80)


if __name__ == "__main__":
    main()